name: Run Test1 Script and Upload to Webflow

on:
  workflow_dispatch:

jobs:
  test1-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb unzip
          pip install -r requirements.txt

      - name: Install Matching Chromedriver
        run: |
          set -e
          CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "Chrome version: $CHROME_VERSION"
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget -N "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip -d /usr/bin/
          chmod +x /usr/bin/chromedriver

      - name: Start Xvfb
        run: Xvfb :99 -ac &
        env:
          DISPLAY: ":99"

      - name: Run Test1 Script
        env:
          START_PAGE: 12498
          CHROMIUM_DRIVER_PATH: /usr/bin/chromedriver
          OUTPUT_DIR: ./scraped_data
          GITHUB_PAT: ${{ secrets.PAT }}
          WEBFLOW_API_TOKEN: ${{ secrets.WEBFLOW_API_TOKEN }}
          WEBFLOW_COLLECTION_ID: ${{ secrets.WEBFLOW_COLLECTION_ID }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          DISPLAY: ":99"
        run: |
          python test1.py
