name: Run Test1 Script and Upload to Webflow

on:
  workflow_dispatch:

jobs:
  test1-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb unzip
          pip install -r requirements.txt

           # Step 4: Install and Configure Chromedriver
      - name: Install Matching Chromedriver
        run: |
          set -e
          # Get major version of Chrome
          CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+\.\d+" | awk -F '.' '{print $1}')
          echo "Chrome major version: $CHROME_VERSION"

          # Get latest compatible ChromeDriver version
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" || echo "unknown")
          if [[ $CHROMEDRIVER_VERSION == "unknown" ]]; then
            echo "No matching ChromeDriver found for Chrome version $CHROME_VERSION. Downgrading Chrome."
            
            # Install the last known stable Chrome version (adjust version as needed)
            sudo apt-get remove -y google-chrome-stable
            wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_116.0.5845.96-1_amd64.deb
            sudo dpkg -i google-chrome-stable_116.0.5845.96-1_amd64.deb
            CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+\.\d+" | awk -F '.' '{print $1}')
            CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          fi

          echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"

          # Download and install ChromeDriver
          wget -N "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip -d /usr/bin/
          chmod +x /usr/bin/chromedriver

      # Step 5: Start Xvfb
      - name: Start Xvfb
        run: Xvfb :99 -ac &
        env:
          DISPLAY: ":99"

      # Step 6: Verify Installation
      - name: Verify Installation
        run: |
          google-chrome --version
          chromedriver --version

      # Step 7: Run the Test1 Script
      - name: Run Test1 Script
        env:
          START_PAGE: 12498
          CHROMIUM_DRIVER_PATH: /usr/bin/chromedriver
          OUTPUT_DIR: ./scraped_data
          GITHUB_PAT: ${{ secrets.PAT }}
          WEBFLOW_API_TOKEN: ${{ secrets.WEBFLOW_API_TOKEN }}
          WEBFLOW_COLLECTION_ID: ${{ secrets.WEBFLOW_COLLECTION_ID }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          DISPLAY: ":99"
        run: |
          python test1.py
