name: Scrape and Upload to Webflow

on:
  workflow_dispatch:

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python Environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # Step 3: Install Chrome and Specific ChromeDriver
      - name: Install Chrome and Specific ChromeDriver
        run: |
          set -e
          echo "Updating system and installing dependencies..."
          sudo apt-get update
          sudo apt-get install -y wget unzip curl

          echo "Adding Google Chrome's repository..."
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update

          echo "Installing Google Chrome (specific version)..."
          sudo apt-get install -y google-chrome-stable=113.0.5672.126-1

          echo "Downloading and installing the specific ChromeDriver version..."
          wget -q https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_linux64.zip
          unzip -o chromedriver_linux64.zip -d /usr/bin/
          chmod +x /usr/bin/chromedriver

          echo "Installed Chrome version:"
          google-chrome --version

          echo "Installed ChromeDriver version:"
          chromedriver --version

      # Step 4: Start Xvfb
      - name: Start Xvfb
        run: |
          echo "Starting Xvfb..."
          Xvfb :99 -ac &
        env:
          DISPLAY: ":99"

      # Step 5: Install Python Dependencies
      - name: Install Dependencies
        run: |
          echo "Installing Python dependencies..."
          pip install -r requirements.txt

      # Step 6: Debug Environment
      - name: Debug Environment
        run: |
          echo "Checking installed Python version:"
          python --version

          echo "Checking installed Chrome version:"
          google-chrome --version

          echo "Checking installed ChromeDriver version:"
          chromedriver --version

          echo "Checking DISPLAY environment variable:"
          echo $DISPLAY

      # Step 7: Run the Test Script
      - name: Run Test Script
        env:
          START_PAGE: 12498
          CHROMIUM_DRIVER_PATH: /usr/bin/chromedriver
          OUTPUT_DIR: ./scraped_data
          GITHUB_PAT: ${{ secrets.PAT }}
          WEBFLOW_API_TOKEN: ${{ secrets.WEBFLOW_API_TOKEN }}
          WEBFLOW_COLLECTION_ID: ${{ secrets.WEBFLOW_COLLECTION_ID }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          DISPLAY: ":99"
        run: |
          echo "Running the scraper script..."
          python test1.py
