name: Run Test1 Script

on:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  test1-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run Test1 Script
        env:
          START_PAGE: 12498
          CHROMIUM_DRIVER_PATH: /usr/bin/chromedriver
          OUTPUT_DIR: ./scraped_data
        run: python test1.py
