name: Run Test1 Script and Upload to Webflow

on:
  workflow_dispatch:

jobs:
  test1-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb unzip wget

      # Step 4: Install a Stable Chrome and ChromeDriver Pair
      - name: Install Chrome and Matching ChromeDriver
        run: |
          # Install Chrome (specific stable version)
          sudo apt-get install -y google-chrome-stable=113.0.5672.126-1
          
          # Download ChromeDriver matching the Chrome version
          wget -q https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_linux64.zip
          unzip -o chromedriver_linux64.zip -d /usr/bin/
          chmod +x /usr/bin/chromedriver

      # Step 5: Start Xvfb
      - name: Start Xvfb
        run: Xvfb :99 -ac &
        env:
          DISPLAY: ":99"

      # Step 6: Verify Installation
      - name: Verify Installation
        run: |
          google-chrome --version
          chromedriver --version

      # Step 7: Run the Test1 Script
      - name: Run Test1 Script
        env:
          START_PAGE: 12498
          CHROMIUM_DRIVER_PATH: /usr/bin/chromedriver
          OUTPUT_DIR: ./scraped_data
          GITHUB_PAT: ${{ secrets.PAT }}
          WEBFLOW_API_TOKEN: ${{ secrets.WEBFLOW_API_TOKEN }}
          WEBFLOW_COLLECTION_ID: ${{ secrets.WEBFLOW_COLLECTION_ID }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          DISPLAY: ":99"
        run: |
          python test1.py
